### ISSUE TITLE
Error in Replicate

### ISSUE THREAD

**Issue by mileshiroo** [camenduru/LGM-replicate#2]
Hi, 

Whenever I run this with any input I get this error now.

```
0%|          | 0/30 [00:00<?, ?it/s]
  3%|▎         | 1/30 [00:00<00:07,  3.82it/s]
 13%|█▎        | 4/30 [00:00<00:02, 11.42it/s]
 23%|██▎       | 7/30 [00:00<00:01, 15.21it/s]
 33%|███▎      | 10/30 [00:00<00:01, 17.36it/s]
 43%|████▎     | 13/30 [00:00<00:00, 18.67it/s]
 53%|█████▎    | 16/30 [00:00<00:00, 19.33it/s]
 63%|██████▎   | 19/30 [00:01<00:00, 19.83it/s]
 73%|███████▎  | 22/30 [00:01<00:00, 20.24it/s]
 83%|████████▎ | 25/30 [00:01<00:00, 20.51it/s]
 93%|█████████▎| 28/30 [00:01<00:00, 20.67it/s]
100%|██████████| 30/30 [00:01<00:00, 18.34it/s]
  0%|          | 0/180 [00:00<?, ?it/s]
 14%|█▍        | 25/180 [00:00<00:00, 244.48it/s]
 36%|███▌      | 64/180 [00:00<00:00, 326.32it/s]
 58%|█████▊    | 105/180 [00:00<00:00, 360.02it/s]
 79%|███████▉  | 142/180 [00:00<00:00, 327.00it/s]
100%|██████████| 180/180 [00:00<00:00, 338.62it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cog/server/runner.py", line 303, in _upload_files
    return self._file_uploader(output)
  File "/usr/local/lib/python3.10/site-packages/cog/server/runner.py", line 212, in file_uploader
    return upload_files(output, upload_file=upload_file)
  File "/usr/local/lib/python3.10/site-packages/cog/json.py", line 53, in upload_files
    return [upload_files(value, upload_file) for value in obj]
  File "/usr/local/lib/python3.10/site-packages/cog/json.py", line 53, in <listcomp>
    return [upload_files(value, upload_file) for value in obj]
  File "/usr/local/lib/python3.10/site-packages/cog/json.py", line 55, in upload_files
    with obj.open("rb") as f:
  File "/usr/local/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'workspace/gradio_output.mp4'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cog/server/runner.py", line 359, in predict
    return _predict(
  File "/usr/local/lib/python3.10/site-packages/cog/server/runner.py", line 433, in _predict
    event_handler.set_output(event.payload)
  File "/usr/local/lib/python3.10/site-packages/cog/server/runner.py", line 246, in set_output
    self.p.output = self._upload_files(output)
  File "/usr/local/lib/python3.10/site-packages/cog/server/runner.py", line 308, in _upload_files
    raise FileUploadError("Got error trying to upload output files") from error
cog.server.runner.FileUploadError: Got error trying to upload output files
```

**Comment by platform-kit** [comment]
@camenduru I'm getting this too. Not just on this model but all my own recent deploys.  Has there been a change in the underlying cog API? Seems file based outputs are broken.
